WITH B AS (
    SELECT B.AUTHOR_ID, B.CATEGORY, (SUM(S.SALES) * B.PRICE) AS TOTAL_PRICE
    FROM BOOK B
    JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
    WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
    GROUP BY B.BOOK_ID
)

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.TOTAL_PRICE) AS TOTAL_SALES
FROM B
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC