WITH FIRST AS (
    SELECT ID
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
), SECOND AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (SELECT * FROM FIRST)
), THIRD AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (SELECT * FROM SECOND)
)

SELECT ID
FROM THIRD
ORDER BY ID;