WITH CANNOT AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%y-%m') = '22-11'
        OR DATE_FORMAT(END_DATE, '%y-%m') = '22-11'
        OR (START_DATE < '2022-11-01' and END_DATE > '2022-11-30')
), THIRTY AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
)

SELECT A.CAR_ID, A.CAR_TYPE, round((A.DAILY_FEE * (100 - B.DISCOUNT_RATE)) * 30 / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN thirty B ON A.CAR_TYPE = B.CAR_TYPE
WHERE A.car_type IN ('세단', 'SUV')
    AND A.CAR_ID NOT IN (SELECT * FROM cannot)
    AND A.DAILY_FEE * (100 - B.DISCOUNT_RATE) / 100 * 30 >= 500000
    AND A.DAILY_FEE * (100 - B.DISCOUNT_RATE) / 100 * 30 < 2000000
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC