SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE SUBSTR(I.SEX_UPON_INTAKE, 1, 6) = 'Intact'
    AND SUBSTR(O.SEX_UPON_OUTCOME, 1, 6) != 'Intact'
ORDER BY I.ANIMAL_ID