WITH SCORES AS (
    SELECT ROUND(AVG(REVIEW_SCORE), 2) AS SCORE, REST_ID
    FROM REST_REVIEW
    GROUP BY REST_ID
)

SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, S.SCORE
FROM REST_INFO I
JOIN SCORES S ON I.REST_ID = S.REST_ID
WHERE SUBSTR(I.ADDRESS, 1, 2) = '서울'
ORDER BY S.SCORE DESC, I.FAVORITES DESC;