WITH A AS (
    SELECT DISTINCT
        YEAR(S.SALES_DATE) AS YEAR,
        MONTH(S.SALES_DATE) AS MONTH,
        I.GENDER AS GENDER,
        I.USER_ID AS USER_ID
    FROM ONLINE_SALE S
        JOIN USER_INFO I ON S.USER_ID = I.USER_ID
    WHERE I.GENDER IS NOT NULL
)

SELECT YEAR, MONTH, GENDER, COUNT(USER_ID) AS USERS
FROM A
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER