WITH USERS AS (
    SELECT USER_ID, YEAR(JOINED)
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
), SALES AS (
    SELECT DISTINCT A.USER_ID, YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH
    FROM ONLINE_SALE A
    JOIN USERS B ON A.USER_ID = B.USER_ID
), TOTAL_USERS AS (
    SELECT COUNT(USER_ID) AS TOTAL
    FROM USERS
)

SELECT YEAR, MONTH, COUNT(USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(USER_ID) / TOTAL, 1) AS PUCHASED_RATIO
FROM SALES, TOTAL_USERS
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;