WITH ING AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= DATE('2022-10-16') AND END_DATE >= DATE('2022-10-16')
    ORDER BY CAR_ID DESC
), TOTAL AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT
    TOTAL.CAR_ID,
    CASE
        WHEN ING.CAR_ID IS NULL THEN '대여 가능'
        ELSE '대여중'
    END AS AVAILABILITY
FROM TOTAL
LEFT JOIN ING ON TOTAL.CAR_ID = ING.CAR_ID
ORDER BY TOTAL.CAR_ID DESC;