WITH B AS (
    SELECT COUNT(*) AS COUNT, HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
)

SELECT A.ID, A.NAME, A.HOST_ID
FROM PLACES A
JOIN B ON A.HOST_ID = B.HOST_ID
WHERE B.COUNT >= 2
ORDER BY A.ID;