WITH A AS (
    SELECT CAR_ID, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
), B AS (
    SELECT DURATION_TYPE AS DURATION, (1 - (DISCOUNT_RATE / 100)) AS RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)

SELECT
    HISTORY_ID,
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90
        THEN FLOOR(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * (SELECT RATE FROM B WHERE DURATION = '90일 이상'))
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30
        THEN FLOOR(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * (SELECT RATE FROM B WHERE DURATION = '30일 이상'))
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7
        THEN FLOOR(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * (SELECT RATE FROM B WHERE DURATION = '7일 이상'))
        ELSE
            FLOOR(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1))
    END AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
JOIN A ON C.CAR_ID = A.CAR_ID
ORDER BY FEE DESC, HISTORY_ID DESC