WITH A AS (
    SELECT APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_YMD
    FROM APPOINTMENT
    WHERE DATE_FORMAT(APNT_YMD, '%y%m%d') = '220413' AND MCDP_CD ='CS' AND APNT_CNCL_YN = 'N'
)

SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM A
JOIN PATIENT P ON A.PT_NO = P.PT_NO
JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
ORDER BY APNT_YMD;