WITH FRONTEND AS (
    SELECT SUM(CODE) AS FRONTENDCODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT FRONTENDCODE FROM FRONTEND)
ORDER BY ID