WITH FRONTEND AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS, FRONTEND
WHERE SKILL_CODE & FRONTEND.CODE
ORDER BY ID