WITH YEAR_SCORE AS (
    SELECT B.EMP_NO, C.EMP_NAME, AVG(SCORE) AS SCORE, C.SAL
    FROM HR_GRADE B
    JOIN HR_EMPLOYEES C ON B.EMP_NO = C.EMP_NO
    GROUP BY B.EMP_NO
)


SELECT EMP_NO, EMP_NAME,
    CASE
        WHEN SCORE >= 96 THEN 'S'
        WHEN SCORE >= 90 THEN 'A'
        WHEN SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN SCORE >= 96 THEN (SAL * 20) / 100
        WHEN SCORE >= 90 THEN (SAL * 15) / 100 
        WHEN SCORE >= 80 THEN (SAL * 10) / 100
        ELSE 0
    END AS BONUS
FROM YEAR_SCORE A;