WITH MAXID AS (
    SELECT A.MEMBER_ID
    FROM REST_REVIEW A
    GROUP BY A.MEMBER_ID
    HAVING COUNT(A.REVIEW_ID) = (
        SELECT COUNT(B.REVIEW_ID)
        FROM REST_REVIEW B
        GROUP BY B.MEMBER_ID
        ORDER BY COUNT(B.REVIEW_ID) DESC
        LIMIT 1)
)

# SELECT *
# FROM MAXID

SELECT C.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW A
JOIN MAXID B ON A.MEMBER_ID = B.MEMBER_ID
JOIN MEMBER_PROFILE C ON A.MEMBER_ID = C.MEMBER_ID
ORDER BY A.REVIEW_DATE, A.REVIEW_TEXT