WITH C AS (
SELECT
    ID,
    (
        SELECT GENOTYPE
        FROM ECOLI_DATA B
        WHERE A.PARENT_ID = ID
    ) AS PARENT_GENOTYPE
FROM ECOLI_DATA A
)

SELECT D.ID, D.GENOTYPE, C.PARENT_GENOTYPE
FROM ECOLI_DATA D
JOIN C ON D.ID = C.ID
WHERE D.PARENT_ID IS NOT NULL AND (D.GENOTYPE | C.PARENT_GENOTYPE = D.GENOTYPE)