WITH MAXS AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_TYPE
), FISHES AS (
    SELECT A.ID, A.FISH_TYPE, B.LENGTH
    FROM FISH_INFO A
    JOIN MAXS B ON A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.LENGTH
)

SELECT B.ID, A.FISH_NAME, B.LENGTH 
FROM FISH_NAME_INFO A
JOIN FISHES B ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY B.ID;
