WITH MAXVIEW AS (
    SELECT MAX(VIEWS) AS VIEWS
    FROM USED_GOODS_BOARD
), MAXBOARD AS (
    SELECT A.BOARD_ID
    FROM USED_GOODS_BOARD A
    JOIN MAXVIEW B ON A.VIEWS = B.VIEWS
)

SELECT CONCAT('/home/grep/src/', A.BOARD_ID, '/', A.FILE_ID, A.FILE_NAME, A.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE A
JOIN MAXBOARD B ON A.BOARD_ID = B.BOARD_ID
ORDER BY A.FILE_ID DESC