SELECT A.CATEGORY,  A.PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A
WHERE A.CATEGORY IN ('과자', '국', '김치', '식용유')
    AND PRICE = (
        SELECT MAX(PRICE)
        FROM FOOD_PRODUCT B
        WHERE A.CATEGORY = B.CATEGORY
        GROUP BY CATEGORY
    )
ORDER BY A.PRICE DESC;